### ISSUE TITLE
A practice ground for Dart-lang

### ISSUE THREAD

**Issue by abhi18av** [domesticmouse/blogger-with-dart#2]
Hi @domesticmouse ,

This issue isn't really related but I wanted to contact you, rather ask your advice regarding DartLang.
I saw that you are the maintainer of the following Go-Dart app https://github.com/google/election-au-2016

Thing is, I really like the language and would like to practice AngularDart2 frontend with a GoLang based backend. I'm a learning the language on my own and GAE is a bit on the expensive side - being a student. Is there any other way I can get real world practice with this stack?

I've looked for a buildpack on Heroku https://elements.heroku.com/buildpacks/igrigorik/heroku-buildpack-dart so, I could probably get some practice there but it's Dart only AFAIK.

Moreover, I know that it should work just as well with any other backend but could you advice me how to set it up for Ruby on Rails and GoLang?  

P.S. Sorry, but the DartLang search isn't extremely informative so I felt I need someone to help me out - hope you don't mind :)

**Comment by domesticmouse** [comment]
Google App Engine Classic is free for sufficiently small request volumes. So, I'd strongly suggest you run your Go backend on GAE, it eliminates a large amount of normal system administration maintenance work that comes with most other solutions in this space.

I know nothing about Heroku, so I can't help you with that path. Thanks!

**Comment by abhi18av** [comment]
Nice! This "classic" did lead me to more useful links

Thank you, I appreciate your advice :smile:

**Comment by domesticmouse** [comment]
All good. Glad I could help!
